runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: public/css
  
- url: /js
  static_dir: public/js

- url: /.well-known/acme-challenge/(.+)
  static_files: public/ssl/acme-challenge/\1
  mime_type: text/plain
  upload: public/ssl/acme-challenge/.*
  application_readable: true
  
- url: /xbower_components
  static_dir: bower_components

- url: /xcustomelements
  static_dir: public/elements

- url: /fonts
  static_dir: public/fonts

- url: /img
  static_dir: public/images

- url: /bower_components
  static_dir: public/app/bower_components

- url: /node_modules
  static_dir: public/app/node_modules

- url: /images
  static_dir: public/app/images

- url: /src
  static_dir: public/app/src
  
- url: /resources
  static_dir: public/resources

- url: /admin/.*
  script: _go_app
  login: admin
  secure: always

- url: /app/.*
  script: _go_app
  login: required
  secure: always

- url: /logout
  script: _go_app
  login: optional
  secure: always

- url: /accesstoken
  script: _go_app
  login: required
  secure: always

- url: /api/.*
  script: _go_app
  login: optional
  secure: always

- url: /.*
  script: _go_app
  login: optional
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- ^(.*/)?.*/bower_components/.*$
- ^(.*/)?.*/utilities/.*$