runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: public/css
  
- url: /js
  static_dir: public/js
  
- url: /bower_components
  static_dir: bower_components

- url: /customelements
  static_dir: public/elements

- url: /fonts
  static_dir: public/fonts

- url: /img
  static_dir: public/images
  
- url: /admin/.*
  script: _go_app
  login: admin

- url: /app/.*
  script: _go_app
  login: required

- url: /.*
  script: _go_app
  login: optional

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- ^(.*/)?.*/bower_components/.*$
- ^(.*/)?.*/utilities/.*$